name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  content: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (specify the version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install dependencies (run from the react project directory)
      - name: Install dependencies
        run: npm install
        working-directory: ./githubactions-react

      # Build the React project (run from the react project directory)
      - name: Build project
        run: npm run build
        working-directory: ./githubactions-react

      # Deploy to GitHub Pages (deploy the dist folder from the react project directory)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./githubactions-react/dist
